apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-lab4
data:
  REACT_APP_USERNAME: Anastasia
  REACT_APP_COMPANY_NAME: ITMO

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lab4
  labels:
    app: lab4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4
  template:
    metadata:
      labels:
        app: lab4
    spec:
      containers:
        - name: lab4
          image: ifilyaninitmo/itdt-contained-frontend:master
          env:
            - name: REACT_APP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cm-lab4
                  key: REACT_APP_USERNAME
            - name: REACT_APP_COMPANY_NAME
              valueFrom:
                configMapKeyRef:
                  name: cm-lab4
                  key: REACT_APP_COMPANY_NAME
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: lab4-svc
spec:
  selector:
    app: lab4
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
  type: LoadBalancer
