apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-manifest
spec:
  tls:
  - hosts:
      - lab3.com
    secretName: l3-secret
  rules:
  - host: lab3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: servic1
            port:
              number: 3000          